### ISSUE TITLE
Charla: Guía Práctica para Convertirse en Contribuidor de Open Source en 10 Años (o más)

### ISSUE THREAD

**Issue by FerPerales** [PythonMexico/python-cdmx-charlas#4]
En una era donde todo mundo buscamos la satisfacción y los resultados inmediatos, compartiré mi camino de 10 años en el ecosistema de Ruby en el que me he convertido de usuario del lenguaje a contribuidor frecuente en una empresa con más de 1,000 millones de descargas de bibliotecas de Ruby.

Los días son largos, pero los años son cortos y, si 10 años no son suficientes para convertirte en contribuidor de Open Source, siempre puedes tomar un año mas y repetir el proceso.

**Comment by pixelead0** [comment]
Se acepta charla para el meetup de Agosto 2024
https://www.meetup.com/es-ES/python-mexico/events/302588415/
